name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Migrations | Apply
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      postgres:
        image: postgres:13.1
        ports: [5432:5432]
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test

    steps:
    - name: Migrations | Checkout
      uses: actions/checkout@v2

    - name: Migrations | .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - run: docker ps -a

    - name: Migrations | Tests
      run: dotnet test
